title: Adewole Benjamin Oyediran
logo: assest/passport1.png
description: Python || Power BI || SQL || Excel ||
#show_downloads: True
#google_analytics:
theme: jekyll-theme-minimal
# SQL Pad Configuration
#sql_pad:
 # title: "SQL Query Pad"
  #description: "select * from sales"
