title: Adewole Benjamin Oyediran
logo: assest/passport1.png
description: Python || Power BI || SQL || Excel || Tableau
#show_downloads: True
#google_analytics:
theme: jekyll-theme-minimal
# SQL Pad Configuration
#sql_pad:
 # title: "SQL Query Pad"
  #description: "select * from sales"

 Custom CSS
head:
  - <link rel="stylesheet" href="/styles.css">  # Link to your custom CSS file
