title: Adewole Benjamin Oyediran
logo: assest/passport1.png
description: Python || Power BI || SQL || Shell ||  Excel || Tableau || Azure
#show_downloads: True
#google_analytics:
#theme: jekyll-theme-minimal
theme                  : minimal-mistakes-jekyll
remote_theme           : mmistakes/minimal-mistakes
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# SQL Pad Configuration
#sql_pad:
 # title: "SQL Query Pad"
  #description: "select * from sales"

# Custom CSS
head:
  - <link rel="stylesheet" href="/styles.css">
