head: - <link rel="stylesheet" href="/styles.css">
title: Adewole Benjamin Oyediran
logo: assest/passport1.png
description: Python || Power BI || SQL || Shell ||  Excel || Tableau || Azure
#show_downloads: True
#google_analytics:
theme: jekyll-theme-minimal


# SQL Pad Configuration
#sql_pad:
 # title: "SQL Query Pad"
  #description: "select * from sales"
